version: '3.8'
services:

  orders:
    build: ./orders
    container_name: orders
    ports:
      - 3005:3005
    env_file:
      - orders/.env
    depends_on:
      - products
    networks:
      - api_network

  products:
    build: ./products
    container_name: products
    ports:
      - 3000:3000
    env_file:
      - products/.env
    depends_on:
      - mongo
    networks:
      - mongo_compose_network
      - api_network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
    env_file:
      - ./products/.env
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - mongo_compose_network

  mongo:
    image: mongo
    environment:
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    env_file:
      - ./products/.env
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo_compose_network

networks: 
    mongo_compose_network:
      driver: bridge
    api_network:
      driver: bridge

volumes:
  mongodb_data: